name: Deploy Telegram Bot

on:
  push:
    branches:
      - release

jobs:
  deploy:
    name: Deploy to VDC
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/wiseman/it_ai_community_bot
            git pull origin release
            source .venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart it-ai-community-bot.service
